- index.html
- 410 unregisters the current report-uri
- 3 failed deliveries unregisters current report-uri
- Logic for immediate vs delayed retry
Closes #14.
> first cut at report-url unregister and retry logic

- index.html
Addresses security and privacy issues raised in #42, #45.
> Restrict NEL to "Potentially Trustworthy" origins

- index.html
I'd like to bring this in line with Reporting in using JSON Field Values instead of CSP-style header values, mostly because I believe JSON parsers (or at least Chromium's) are more well-tested than one-off parsers written for CSP-style values.
> Move from CSP-style format to JSON Field Values

- index.html
This is the only field in any of the JSON payloads that uses CamelCase.  Change it to use kebab-case like everything else.
This is a purely cosmetic change.
> Rename includeSubdomains to include-subdomains

- index.html
This should hopefully take care of #68.  Uses `data-cite` and `[[references]]` for everything now, and adds a separate section at the beginning that lists all external terms, along with the specs that define them.
> Eliminate all custom reference links

- index.html
I propose that the user agent should report on successful requests in addition to ones that result in a network error.  When responding to alerts generated from these reports, we typically need to know about the _rate_ of errors, not just the raw _count_ of them.  And to get a rate, you need a denominator that includes successful requests.
I think this has been discussed previously, and we left this out of the spec because the origin server already has information about successful requests in its server logs.  However, joining the data from the server logs and from any NEL report collector is non-trivial.  And it precludes using a third-party service as your NEL report collector, since that external service wouldn't have access to your server logs.
This proposal also adds sampling rates …
> Add successes and sampling rates

- index.html
This is a TAG recommendation now.  We've already updated Reporting to use underscores, so NEL should follow suit.
> Update JSON field names to use underscores instead of dashes

- index.html
This pulls the definition of a NEL report out into its own section, instead of having the definition buried inside of the "when to generate a report" algorithm.
> Refactor report definition

- index.html
This updates the spec to follow the same basic structure as Reporting, with a separate top-level Concepts section, and separate sections on Policy Delivery and Report Delivery.
> Factor out a Concepts section

- index.html
NEL has been adopted by the Web Performance Working Group, and is therefore now an Editor's Draft instead of a Community Group Draft.  Addresses #86
> Update WICG references to W3C

- index.html
This patch clarifies the different phases that happen while servicing a request.  A network error occurs during one of those phases, and we now handle errors differently depending on which phase they occur in:
- `include_subdomains` policies can only be used to generate reports about DNS resolution errors, since the policy author can only confirm ownership of the DNS tree, and not of all of the servers that those domain names resolve to.
- If the resolved IP address for an origin changes between when a policy is received, and when its used to generate a report, we don't report any details about the `connection` and `application` phases, and only report that the IP address changed.  This prevents DNS rebinding attacks.
> Handle errors in different phases differently

- index.html
State this explicitly (even though it's the default), and add a note explaining why, to help ensure that we don't accidentally remove this restriction in the future.
> NEL reports are not observable

- index.html
It got removed during a recent cleanup PR, and we need it to be able to say that they're not observable.
> Clean up network error reports section

- index.html
This would address #72.  The Chrome implementation already does this, but I don't have a strong opinion either way, since we could always translate `ok` → `http.error` on the collector side, too.  I think we should get rid of the current language (5xx MAY be an error) either way — it should either always be considered an error, or always be considered a success.
> Require 4xx and 5xx results to be `http.error`

- index.html
- We don't need to downgrade a report to `dns` if it's already `dns`.
- We don't need to follow the special `include_subdomains` logic if the report and policy have the same origin (i.e., if the policy would've still been used had `include_subdomains` not been set).
> Add extra constraints to report generation algorithm

- index.html
So bikeshed specs can more easily depend on it.
Used in https://github.com/WICG/webpackage/pull/374, and https://github.com/tabatkins/bikeshed/issues/1422 asks to index the spec as a whole.
> Export "Generate a network error report".

- index.html
I want to introduce an OPTIONAL `additional body` to the algorithm of "Generate a network error report".
This will be used to send the signed exchange reports https://github.com/w3c/network-error-logging/issues/99 from the spec of "Loading Signed Exchanges" https://github.com/WICG/webpackage/pull/374.
***
<a href="https://pr-preview.s3.amazonaws.com/horo-t/network-error-logging/pull/100.html" title="Last updated on Jan 29, 2019, 3:19 AM UTC (ded837b)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/network-error-logging/100/49c04de...horo-t:ded837b.html" title="Last updated on Jan 29, 2019, 3:19 AM UTC (ded837b)">Diff</a>
> Introduce a new algorithm "Deliver a network report".

- index.html
ReSpec now takes a short name for the WG responsible for this document, rather than a set of configuration parameters. Updated to "webperf".
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/network-error-logging/pull/128.html" title="Last updated on Nov 23, 2020, 8:54 PM UTC (78e62e1)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/network-error-logging/128/538e371...78e62e1.html" title="Last updated on Nov 23, 2020, 8:54 PM UTC (78e62e1)">Diff</a>
> Update WG ReSpec config

- index.html
This CL moves the subdomain check -- which is supposed to ensure that only DNS errors are reported for subdomains -- before the step which can downgrade reports, since that step can change some reports into DNS reports, even they were not originally.
Closes: #141
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/network-error-logging/pull/144.html" title="Last updated on Jun 7, 2023, 9:47 PM UTC (0fd893e)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/network-error-logging/144/09c74af...0fd893e.html" title="Last updated on Jun 7, 2023, 9:47 PM UTC (0fd893e)">Diff</a>
> Ensure that subdomain policies are only for DNS.

- index.html
Fixes a few broken refs.
Closes: #131 
(Also addresses most of #132)
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/network-error-logging/pull/145.html" title="Last updated on Jun 8, 2023, 12:13 AM UTC (c491ecf)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/network-error-logging/145/09c74af...c491ecf.html" title="Last updated on Jun 8, 2023, 12:13 AM UTC (c491ecf)">Diff</a>
> Fix broken references

- index.html
This removes the processing step in Extract Response Headers which also adds HTTP trailer fields to the report. Trailers are no longer exposed by Fetch, which this builds on, and generally not supported on the Web.
Closes: #146
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/network-error-logging/pull/148.html" title="Last updated on Jun 9, 2023, 5:44 PM UTC (6bc150c)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/network-error-logging/148/f1209d7...6bc150c.html" title="Last updated on Jun 9, 2023, 5:44 PM UTC (6bc150c)">Diff</a>
> Remove trailer processing

- index.html
This attemps to ensure that an attacker who can inject a NEL policy for a small time window cannot cause that policy to persist forever. All policies will have a 48h "freshness" window, after which they need to be refreshed. When stale, they will still be used to send a final report, if a network error occurs, as long as they are not expired (that is, while they are still within their `max_age` expiry time).
Closes: #139
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/network-error-logging/pull/147.html" title="Last updated on Jun 27, 2023, 2:29 PM UTC (ec59243)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/network-error-logging/147/f1209d7...ec59243.html" title="Last updated on Jun 27, 2023, 2:29 PM UTC (ec59243)">Diff</a>
> Make NEL policies stale after 48h

- index.html
This corrects several links to "phase", which were pointing to the wrong concept, and links several unlinked uses of the word.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/network-error-logging/pull/158.html" title="Last updated on Sep 14, 2023, 5:52 PM UTC (282248f)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/network-error-logging/158/fa02761...282248f.html" title="Last updated on Sep 14, 2023, 5:52 PM UTC (282248f)">Diff</a>
> Fix links to "phase"

- index.html
This removes from NEL reports the fields which are not relevant to a given error, given the connection phase.
Closes: #105
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/network-error-logging/pull/164.html" title="Last updated on Sep 27, 2023, 9:11 PM UTC (61df9cb)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/network-error-logging/164/855a35b...61df9cb.html" title="Last updated on Sep 27, 2023, 9:11 PM UTC (61df9cb)">Diff</a>
> Remove unnecessary fields and URL parts

- index.html
This hails back to a previous version of the spec at d22a1b1d053de43ec6e98c92c52ca8080c06a6ba.
The TODO was added a bit before that (https://github.com/w3c/network-error-logging/commit/df0af4631caa4fcc54bee5bbe39f1c8a4e289e2d).
***
<a href="https://pr-preview.s3.amazonaws.com/miketaylr/network-error-logging/pull/179.html" title="Last updated on Feb 4, 2025, 2:05 AM UTC (9cc0258)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/network-error-logging/179/a19bf38...miketaylr:9cc0258.html" title="Last updated on Feb 4, 2025, 2:05 AM UTC (9cc0258)">Diff</a>
> Remove settings from example report

- index.html
It uses [ReSpec index feature](https://respec.org/docs/#id-index) combined with [xref](https://respec.org/docs/#xref) to maintain links with other well-known specs. For specs that aren't part of xref, I've chosen to use `<a data-cite>` when there was a single occurrence, and use a `<dfn data-cite>` in the first linked occurrence when there was several of them
***
<a href="https://pr-preview.s3.amazonaws.com/dontcallmedom/network-error-logging/pull/171.html" title="Last updated on Nov 14, 2023, 10:25 AM UTC (cbca3bd)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/network-error-logging/171/de1c106...dontcallmedom:cbca3bd.html" title="Last updated on Nov 14, 2023, 10:25 AM UTC (cbca3bd)">Diff</a>
> Replace manual list of dependencies by automatically generated index

- index.html
Fixes the issue mentioned in #189 .
***
<a href="https://pr-preview.s3.amazonaws.com/PontusHanssen/network-error-logging/pull/190.html" title="Last updated on Mar 12, 2025, 9:11 AM UTC (c31b167)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/network-error-logging/190/d8a9916...PontusHanssen:c31b167.html" title="Last updated on Mar 12, 2025, 9:11 AM UTC (c31b167)">Diff</a>
> Correct sample rate calculation comparison

- index.html
This is Part 1 of N commits to address #166. 
It largely just links to existing Fetch concepts.
***
<a href="https://pr-preview.s3.amazonaws.com/miketaylr/network-error-logging/pull/182.html" title="Last updated on May 5, 2025, 6:19 PM UTC (20b68d2)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/network-error-logging/182/dd40179...miketaylr:20b68d2.html" title="Last updated on May 5, 2025, 6:19 PM UTC (20b68d2)">Diff</a>
> Issue #181 - Redefine network request in terms of Fetch
